using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;
using Playcus.Utils;
using Playcus;
#if PL_SDK_PLAYCUSDATALAKE_ON
using Playcus.Support;
using PlaycusDL;
#endif
#if PL_SDK_DELTADNA_ON
using DeltaDNA;
#endif
#if UNITY_EDITOR
using UnityEditor;

#endif

namespace Playcus.Analytics
{
    /// <summary>
    /// For AnalyticsService used only! Don't use directly! (Simonenko Alexey, Alexander Dorokhov)
    /// </summary>
    public class PlaycusDataLakeAnalyticServicePlatform : AnalyticsServicePlatform
    {
        public override bool CanTesterBeTracked()
        {
            return true;
        }


        [Serializable]
        public sealed class Configuration
        {
            public string environmentKeyDev;
            public string environmentKeyLive;
        }

        // CONFIG
        [Header("Settings")]
        [SerializeField] private bool GetDeviceAndAdIdByPDL = true;

        // LEGACY - now this settings generated by Project Config
        private PlaycusDataLakeAnalyticServicePlatform.Configuration configuration;


#if PL_SDK_PLAYCUSDATALAKE_ON
        // PRIVATE
        private Action initCallbackFunction;
        [InjectService] private IAnalyticsManager _analyticsManager;
        [InjectService] private ProjectConfig _projectConfig;

        private const string CollectUrl = "https://datalake.playcus.com/stat_core/pdlqueue.php";
        private const string HashSecret = "";


        /// <summary>
        /// Constructor
        /// </summary>
        public override void TryToInit()
        {
            if (IsInited)
                return;

            ServiceLocator.ResolveServicesInComponent(this);

            _analyticsManager.LogDebug("PlaycusDataLakeAnalyticServicePlatform init", true);
            try
            {
#if UNITY_EDITOR_WIN
                    PDL.Instance.Platform = PlaycusDL.Platform.PC_CLIENT;
#elif UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX
                    PDL.Instance.Platform = PlaycusDL.Platform.MAC_CLIENT;
#elif UNITY_WSA
                    PDL.Instance.Platform = PlaycusDL.Platform.WINDOWS_MOBILE;
#elif STORE_Amazon
                    PDL.Instance.Platform = PlaycusDL.Platform.AMAZON;
#endif
                    PlaycusDL.ConfigurationPDL sdkConfiguration = new PlaycusDL.ConfigurationPDL();
                    sdkConfiguration.environmentKey = _analyticsManager.IsTesterUser() ? 0 : 1;
                    sdkConfiguration.useApplicationVersion = true;
                    sdkConfiguration.collectUrl = CollectUrl;
                    if (_projectConfig != null && !string.IsNullOrEmpty(_projectConfig.ProjectCode))
                    {
                        // Generate PDL Databases urls by project code
                        sdkConfiguration.environmentKeyDev = $"{_projectConfig.ProjectCode}_dev";
                        sdkConfiguration.environmentKeyLive = $"{_projectConfig.ProjectCode}_prod";
                    }
                    else
                    {
                        // Legacy fallback
                        sdkConfiguration.environmentKeyDev = configuration.environmentKeyDev;
                        sdkConfiguration.environmentKeyLive = configuration.environmentKeyLive;
                    }

                    sdkConfiguration.hashSecret = HashSecret;
                    PDL.Instance.StartSDK(sdkConfiguration);

                    if (GetDeviceAndAdIdByPDL)
                    {
                        PDL.Instance.DeviceID = SystemInfo.deviceUniqueIdentifier;
#if UNITY_WSA && ENABLE_WINMD_SUPPORT
                        PDL.Instance.AdvertisingID = Windows.System.UserProfile.AdvertisingManager.AdvertisingId;
#else
                        Application.RequestAdvertisingIdentifierAsync((advertisingId, trackingEnabled, error) =>
                        {
                            PDL.Instance.AdvertisingID = advertisingId;
                        });
#endif
                    }

                    InitComplete();
                    
                    var userInfoService = ServiceLocator.Get<IUserInfoService>();
                    if (userInfoService != null)
                    {
                        _analyticsManager.LogDebug(
                            $"PlaycusDataLakeAnalyticServicePlatform InitComplete. userID:{userInfoService.UserID}, deviceID:{PDL.Instance.DeviceID}, sessionID:{PDL.Instance.SessionID}",
                            true);
                    }
                    else
                    {
                        Debug.LogError($"PlaycusDataLakeAnalyticServicePlatform: Can’t get UserID, because IUserInfoService is null");
                        _analyticsManager.LogDebug(
                            $"PlaycusDataLakeAnalyticServicePlatform InitComplete. userID: NULL, deviceID:{PDL.Instance.DeviceID}, sessionID:{PDL.Instance.SessionID}",
                            true);
                    }
                    

            }
            catch (Exception e)
            {
                Debug.LogError($"PlaycusDataLakeAnalyticServicePlatform: init error {e.Message}", gameObject);
            }
        }

        public override void TrackEvent(AnalyticsEvent currentEvent)
        {
            try
            {
                // Purchase is special event
                if (currentEvent.EventKey == AnalyticsEvents.pl_purchase_success.ToString())
                {
                    PurchaseSuccess(
                        currentEvent.pr_currency,
                        currentEvent.pr_revenue,
                        currentEvent.pr_content_id,
                        currentEvent.pr_content_type,
                        currentEvent.pr_placement,
                        currentEvent.pr_receipt
                    );
                }
                // else
                // {
                    //Custom event
                    var gameEvent = new GameEventPDL(currentEvent.EventKey);
                    // Dictionary<string, string> eventParameters = new Dictionary<string, string>();
                    // int i = 0;
                    foreach (KeyValuePair<string, object> kvp in currentEvent.Parameters)
                    {
                        gameEvent.AddParam(kvp.Key, kvp.Value);
                        // i++;
                    }

                    PDL.Instance.RecordEvent(gameEvent).Run();
                // }
            }
            catch (Exception e)
            {
                Debug.Log("PlaycusDataLakeAnalyticServicePlatform: Exception", gameObject);
                Debug.Log(e.ToString(), gameObject);
                throw;
            }
        }

        private void PurchaseSuccess( string currency, string price, string itemID, string itemType, string placement, string receipt)
        {
            // SDK validated events
#if UNITY_IOS && !UNITY_EDITOR
            /*
            IOS (Apple App Store)
            To validate in-app purchases made through the Apple App Store the following parameters should be added to the transaction event:

            transactionServer - the server for which the receipt should be validated against, in this case 'APPLE'
            transactionReceipt - the purchase data as a string not as nested JSON
            transactionID - the ID of the in-app purchase e.g 100000576198248
            */

            // Deserialize ios receipt
            JSONNode receiptParsed = JSON.Parse(receipt);
            // Prepare event
            var gameEvent = new TransactionPDL(
                itemID,
                "PURCHASE",
                new ProductPDL()
                    .AddItem(itemID,
                                string.IsNullOrEmpty(itemType) ? "item" : itemType,
                                string.IsNullOrEmpty(placement) ? "shop" : placement,
                                1),
                new ProductPDL()
                    .SetRealCurrency(currency, ProductPDL.ConvertCurrency(currency, Convert.ToDecimal(float.Parse(price, System.Globalization.CultureInfo.InvariantCulture)))))
            .SetServer("APPLE")
            .SetReceipt(receipt)
            .SetProductId(itemID);
#elif UNITY_ANDROID && STORE_GooglePlay && !UNITY_EDITOR
            /*
             Android (Google Play Store)
             To validate in-app purchases made through the Google Play Store the following parameters should be added to the transaction event:

             transactionServer - the server for which the receipt should be validated against, in this case 'GOOGLE'
             transactionReceipt - the purchase data as a string
             transactionReceiptSignature - the in-app data signature
             iOS (Apple App Store)
             */

            // Deserialize android receipt
            JSONNode receiptParsed = JSON.Parse(receipt);
            JSONNode payload = JSON.Parse(receiptParsed["Payload"]);
            // Prepare event
            var gameEvent = new TransactionPDL(
                itemID,
                "PURCHASE",
                new ProductPDL()
                    .AddItem(itemID,
                                string.IsNullOrEmpty(itemType) ? "item" : itemType,
                                string.IsNullOrEmpty(placement) ? "shop" : placement,
                                1),
                new ProductPDL()
                    .SetRealCurrency(currency, ProductPDL.ConvertCurrency(currency, Convert.ToDecimal(float.Parse(price, System.Globalization.CultureInfo.InvariantCulture)))))
            .SetServer("GOOGLE")
            .SetReceipt(receipt)
            .SetReceiptSignature(payload["signature"])
            .SetProductId(itemID);
#else

            // Prepare event without validation
            if (string.IsNullOrEmpty(receipt))
            {
                receipt = StoreConstants.GetCurrentStore().ToString() + " empty receipt";
            }
            var gameEvent = new TransactionPDL(
                        itemID,
                        "PURCHASE",
                        new ProductPDL()
                            .AddItem(itemID,
                                string.IsNullOrEmpty(itemType) ? "item" : itemType,
                                string.IsNullOrEmpty(placement) ? "shop" : placement,
                                1),
                        new ProductPDL()
                            .SetRealCurrency(currency, ProductPDL.ConvertCurrency(currency,
                                Convert.ToDecimal(float.Parse
                                    (price, System.Globalization.CultureInfo.InvariantCulture)))))
                    .SetServer(StoreConstants.GetCurrentStore().ToString())
                    .SetReceipt(receipt)
                    .SetProductId(itemID)
                ;

#endif

            PDL.Instance.RecordEvent(gameEvent).Run();
        }


#else
        public override void TryToInit()
        {
            Debug.LogError("Insert PL_SDK_PLAYCUSDATALAKE_ON scriptable symbol in project settings");
        }

        public override void TrackEvent(AnalyticsEvent currentEvent){}


        [HelpBox(@"Insert PL_SDK_PLAYCUSDATALAKE_ON scriptable symbol in project settings", HelpBoxMessageType.Warning)]
#endif
        [SerializeField] private bool _iSeeThisAlert;
    }
}